// <auto-generated />
namespace TorontoBeerDirectory.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class brewerybeer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(brewerybeer));
        
        string IMigrationMetadata.Id
        {
            get { return "202401301554028_brewery-beer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
